config/routes.rb
Rails.application.routes.draw do
  get 'join', to: 'users#new', as: :join
  post 'join', to: 'users#create'
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  root to: 'rooms#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :speaker, class_name: 'User', foreign_key: 'speaker_id', optional: true

  def owned_by?(user)
    speaker.present? && speaker == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, class_name: 'Message', foreign_key: 'speaker_id'
  has_secure_password

  validates :name, format: { with: /\A[a-zA-Z0-9]+\z/, message: 'only allows letters and numbers' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: session_params[:name])

    if user&.authenticate(session_params[:password])
      login(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:name, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    logout
    cookies.encrypted[:user_id] = user.id
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||=  User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def logout
    cookies.encrypted[:user_id] = nil
    reset_session
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Hi <%= logged_in? ? current_user.name : 'guest' %></h1>
    <% if logged_in? %>
      <%= link_to 'Logout', logout_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', login_path %> or <%= link_to 'Join', join_path %>
    <% end %>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<% owned ||= false %>
<div class="message">
  <p>
    <span class="message__speaker <%= owned ? '-is-owner' : '' %>">
      <%= message.speaker&.name || 'guest' %>:
    </span>
    <%= message.content %>
  </p>
</div>

app/views/rooms/show.html.erb
<h1>Chat room</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render partial: 'messages/message', locals: { message: message, owned: message.owned_by?(current_user) } %>
  <% end %>
</div>

<form>
  <label>Say something:</label><br>
  <input type="text" data-behavior="room_speaker">
</form>

app/views/users/new.html.erb
<h1>Join us!</h1>

<% if @user.errors.present? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user, url: join_path, local: true do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit 'Join!'%>
  </div>
<% end %>